In [9]:
import nbimporter
import importlib
import Stock_data_puller
%load_ext autoreload
%autoreload 2

In [ ]:
stock_data_universe = pd.read_csv(r'C:\Users\40100171\OneDrive - Anheuser-Busch InBev\Desktop\Technical_Analysis_automated')

In [10]:
data = Stock_data_puller.data_puller('alkem.ns', start_date='2024-01-01', end_date='2024-02-01', interval='1d')

[*********************100%%**********************]  1 of 1 completed

C:\Users\40100171\AppData\Local\anaconda3\Lib\site-packages\yfinance\utils.py:788: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

,Open,High,Low,Close,Adj Close,Volume,Stock Name
Date,,,,,,,
2024-01-01,5209.950195,5225.000000,5093.200195,5120.000000,5081.784180,101017,alkem.ns
2024-01-02,5135.000000,5199.899902,5113.850098,5186.000000,5147.291504,101061,alkem.ns
2024-01-03,5201.950195,5266.950195,5156.200195,5240.500000,5201.384277,275095,alkem.ns
2024-01-04,5240.500000,5301.000000,5228.600098,5269.450195,5230.119141,442884,alkem.ns
2024-01-05,5275.000000,5315.500000,5202.950195,5238.600098,5199.499023,223430,alkem.ns
2024-01-08,5230.000000,5235.350098,5150.549805,5203.549805,5164.710449,50216,alkem.ns
2024-01-09,5230.000000,5268.700195,5165.549805,5178.549805,5139.896973,159805,alkem.ns
2024-01-10,5222.899902,5225.000000,5073.000000,5119.799805,5081.585449,215333,alkem.ns
2024-01-11,5128.049805,5156.049805,5030.500000,5057.750000,5019.998535,147170,alkem.ns
2024-01-12,5072.250000,5230.000000,5012.000000,5048.700195,5011.016602,138930,alkem.ns
2024-01-15,5048.100098,5054.350098,4968.000000,5037.600098,4999.999023,227660,alkem.ns
2024-01-16,5037.950195,5080.350098,5023.649902,5060.600098,5022.827637,100552,alkem.ns
2024-01-17,5060.600098,5104.450195,5014.000000,5056.149902,5018.410645,110342,alkem.ns
2024-01-18,5056.149902,5072.600098,4908.350098,4933.850098,4897.023438,153745,alkem.ns
2024-01-19,4974.950195,4974.950195,4904.250000,4964.299805,4927.246094,114591,alkem.ns
2024-01-23,4878.700195,4956.000000,4763.250000,4815.700195,4779.755371,206809,alkem.ns
2024-01-24,4860.200195,5022.100098,4816.500000,4999.600098,4962.282715,230011,alkem.ns
2024-01-25,4999.600098,5044.850098,4934.600098,4971.750000,4934.640625,213702,alkem.ns
2024-01-29,4998.649902,5022.899902,4940.450195,4975.350098,4938.213867,62787,alkem.ns
2024-01-30,4975.000000,4997.450195,4906.000000,4946.299805,4909.380371,164802,alkem.ns
2024-01-31,4990.000000,5087.950195,4972.000000,4996.049805,4958.759277,263753,alkem.ns